# # Base profile
# TrajectoryPlannerROS:
#   acc_lim_x: 1.0
#   acc_lim_y: 0.0
#   acc_lim_theta: 1.0
#   max_vel_x: 0.3
#   min_vel_x: 0.0
#   max_vel_y: 0.0
#   min_vel_y: 0.0
#   max_vel_theta: 1.0
#   min_vel_theta: -1.0
#   min_in_place_vel_theta: 0
#   holonomic_robot: false
#   dwa: false

#   # Goal Tolerance Parameters
#   yaw_goal_tolerance: 6.28 # (5 degrees) The tolerance in radians for the controller in yaw/rotation when achieving its goal
#   xy_goal_tolerance: 0.10 # (10cm) The tolerance in meters for the controller in the x & y distance when achieving a goal
#   latch_xy_goal_tolerance: false # If goal tolerance is latched, if the robot ever reaches the goal xy location it will simply rotate in place, even if it ends up outside the goal tolerance while it is doing so.

#   # forward simulation
#   sim_time: 1.7
#   sim_granularity: 0.025
#   angular_sim_granularity: 0.025
#   vx_samples: 5
#   vtheta_samples: 20

#   ## scoring (defaults)
#   meter_scoring: true
#   path_distance_bias: 5.0 # 3 # 0.5
#   goal_distance_bias: 5.0 #1.5 #0.75

#   pdist_scale: 5.0
#   gdist_scale: 5.0
#   occdist_scale: 0.01

#   heading_lookahead: 0.325
#   heading_scoring_timestep: 0.8
#   heading_scoring: true
# Base profile
base_local_planner: "dwa_local_planner/DWAPlannerROS"
DWAPlannerROS:
  acc_lim_theta: 1.0
  acc_lim_trans: 0.1
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  angular_sim_granularity: 0.1
  forward_point_distance: 0.325
  goal_distance_bias: 5.0
  max_scaling_factor: 0.2
  max_vel_theta: 1.0
  max_vel_trans: 0.55
  max_vel_x: 0.3
  max_vel_y: 0.0
  min_vel_theta: 0.0
  min_vel_trans: 0.1
  min_vel_x: 0.0
  min_vel_y: 0.0
  occdist_scale: 0.02
  oscillation_reset_angle: 0.2
  oscillation_reset_dist: 0.05
  path_distance_bias: 5.0
  prune_plan: false
  restore_defaults: false
  scaling_speed: 0.25
  sim_granularity: 0.025
  sim_time: 1.7
  stop_time_buffer: 0.2
  theta_stopped_vel: 0.1
  trans_stopped_vel: 0.1
  twirling_scale: 0.0
  use_dwa: false
  vth_samples: 20
  vx_samples: 3
  vy_samples: 10
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
