planners:
  - name: GlobalPlanner
    type: global_planner/GlobalPlanner

controllers:
  - name: DWAPlannerROS
    type: dwa_local_planner/DWAPlannerROS

controller_frequency: 7.0
controller_patience: 10.0

planner_frequency: 1.0
planner_patience: 10.0

oscillation_timeout: 10.0
oscillation_distance: 0.2
